-----WILDCARD AND SPECIAL OPERATORS

--1 TASK
SELECT * FROM salesman
WHERE city = ' Paris' OR city = ' Rome'

--2 TASK
SELECT * FROM salesman
WHERE city = ' Paris' OR city = ' Rome'

--3 TASK
SELECT * FROM salesman
WHERE city NOT IN (' Paris', ' Rome')

--4 TASK
SELECT * FROM customer
WHERE customer_id IN (3007, 3008, 3009)

--5 TASK
SELECT * FROM salesman
WHERE commission BETWEEN 0.12 AND 0.14

--6 TASK
SELECT * FROM orders
WHERE purch_amt BETWEEN 500 AND 4000 AND purch_amt NOT IN (948.50, 1983.43)

--7 TASK
SELECT * FROM salesman
WHERE name BETWEEN 'A' and 'L'

--8 TASK
SELECT * FROM salesman
WHERE name NOT BETWEEN 'A' and 'M'

--9 TASK
SELECT * FROM customer
WHERE cust_name LIKE 'B%'

--10 TASK
SELECT * FROM customer
WHERE cust_name LIKE '%N'

--11 TASK
SELECT * FROM salesman
WHERE name LIKE 'N__L%'

--20 TASK
SELECT * FROM customer
WHERE grade IS NULL

--21 TASK
SELECT * FROM customer
WHERE grade IS NOT NULL

--22 TASK
SELECT * FROM emp_details
WHERE EMP_LNAME LIKE 'D%'

-----SORT FILTER
--1 TASK
SELECT CONCAT(FIRST_NAME,LAST_NAME) AS Full_Name, SALARY FROM employees
WHERE SALARY < 6000

--2 TASK
SELECT FIRST_NAME, LAST_NAME,DEPARTMENT_ID, SALARY FROM employees
WHERE SALARY > 8000

--3 TASK
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM employees
WHERE LAST_NAME = ' McEwen'

--4 TASK
SELECT * FROM employees
WHERE DEPARTMENT_ID IS NULL

--5 TASK
SELECT * FROM departments
WHERE DEPARTMENT_NAME = 'Marketing'

--6 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, HIRE_DATE,SALARY,DEPARTMENT_ID FROM employees
WHERE FIRST_NAME NOT LIKE '%M%'
ORDER BY DEPARTMENT_ID

--7 TASK
SELECT * FROM employees
WHERE SALARY BETWEEN 8000 AND 12000
	AND COMMISSION_PCT IS NOT NULL
	OR DEPARTMENT_ID NOT IN (40, 70, 120)
	AND HIRE_DATE < '1987-06-05'

--8 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, SALARY FROM employees
WHERE COMMISSION_PCT IS NULL

--9 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name,CONCAT(PHONE_NUMBE, ' - ', EMAIL) AS Contact_Details,SALARY FROM employees
WHERE SALARY BETWEEN 9000 AND 17000

--10 TASK
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE FIRST_NAME LIKE '%M'

--11 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, SALARY FROM employees
WHERE SALARY NOT BETWEEN 7000 AND 15000
ORDER BY Full_Name

--12 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, JOB_ID, HIRE_DATE FROM employees
WHERE HIRE_DATE BETWEEN '2007-11-05' AND '2009-07-05'

--13 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, DEPARTMENT_ID FROM employees
WHERE DEPARTMENT_ID = 70 OR DEPARTMENT_ID = 90

--14 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, SALARY, MANAGER_ID FROM employees
WHERE MANAGER_ID IS NOT NULL

--15 TASK
SELECT * FROM employees
WHERE HIRE_DATE < '2002-06-21'

--16 TASK
SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY, MANAGER_ID FROM employees
WHERE MANAGER_ID IN (120, 103, 145)

--17 TASK
SELECT * FROM employees
WHERE FIRST_NAME LIKE '%D%'
	OR FIRST_NAME LIKE '%S%'
	OR FIRST_NAME LIKE '%N%'
ORDER BY SALARY DESC

--18 TASK
SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_Name, HIRE_DATE, COMMISSION_PCT, 
CONCAT(EMAIL, '- ', PHONE_NUMBE) AS Contact_details, SALARY
FROM employees
WHERE SALARY > 11000 OR PHONE_NUMBE LIKE '______3%'
ORDER BY FIRST_NAME DESC

--19 TASK
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM employees
WHERE FIRST_NAME LIKE '___S%'

--20 TASK
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPARTMENT_ID FROM employees
WHERE DEPARTMENT_ID NOT IN (50,30,80)

--21 TASK
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPARTMENT_ID FROM employees
WHERE DEPARTMENT_ID IN (30,40,90)

--22 TASK
SELECT EMPLOYEE_ID FROM job_history
GROUP BY EMPLOYEE_ID
HAVING COUNT(EMPLOYEE_ID)>=2

--23 TASK
SELECT JOB_ID, COUNT(JOB_ID) AS count, SUM(SALARY) AS sum, (MAX(SALARY) - MIN(SALARY)) AS salary_difference
FROM employees
GROUP BY JOB_ID

--24 TASK
SELECT JOB_ID FROM job_history
WHERE DATEDIFF(DAY,START_DATE,END_DATE) > 300
GROUP BY JOB_ID
HAVING COUNT(*)>=2

--25 TASK
SELECT COUNTRY_ID, COUNT(*) AS count
FROM locations
GROUP BY COUNTRY_ID

--26 TASK
SELECT MANAGER_ID, COUNT(*) FROM employees
GROUP BY MANAGER_ID

--27 TASK
SELECT * FROM jobs
ORDER BY JOB_TITLE DESC

--28 TASK
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees
WHERE JOB_ID IN (' SA_REP', ' SA_MAN')

--29 TASK
SELECT DEPARTMENT_ID, AVG(SALARY) 
FROM employees
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID

--30 TASK
SELECT DISTINCT(DEPARTMENT_ID) FROM employees
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) >= 4

--31 TASK
SELECT DEPARTMENT_ID FROM employees
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(COMMISSION_PCT) > 10

--32 TASK
SELECT EMPLOYEE_ID, MAX(END_DATE) AS Max FROM job_history
	WHERE EMPLOYEE_ID IN (
		SELECT EMPLOYEE_ID FROM job_history
		GROUP BY EMPLOYEE_ID
		HAVING COUNT(EMPLOYEE_ID)>1
	)
GROUP BY EMPLOYEE_ID

--33 TASK
SELECT * FROM employees
WHERE COMMISSION_PCT IS NULL
	AND SALARY BETWEEN 7000 AND 12000
	AND DEPARTMENT_ID = 50

--34 TASK
SELECT JOB_ID, AVG(SALARY) AS Avg_salary FROM employees
GROUP BY JOB_ID
HAVING AVG(SALARY) >= 8000

--35 TASK
SELECT JOB_TITLE, MAX_SALARY - MIN_SALARY AS salary_difference FROM jobs
WHERE MAX_SALARY BETWEEN 12000 AND 18000

--36 TASK
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE FIRST_NAME LIKE ' D%' OR LAST_NAME LIKE ' D%'

--37 TASK
SELECT * FROM jobs
WHERE MIN_SALARY > 9000

--38 TASK
SELECT * FROM employees
WHERE HIRE_DATE > '1987-09-07'